# Generated by Django 4.0.1 on 2022-01-15 06:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Other'), ('D', 'Prefer not to say')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_change',
            field=models.DateTimeField(auto_now=True, verbose_name='last name change'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_cont',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(choices=[('Male', models.ImageField(default='male.jpg', upload_to='')), ('Female', models.ImageField(default='female.jpg', upload_to='')), ('Turtle', models.ImageField(default='turtle.jpg', upload_to=''))], default='default.jpg', upload_to=''),
        ),
    ]
